### ISSUE TITLE
Groundfloor official statement

### ISSUE THREAD

**Issue by jleclanche** [ghuntley/affectedbysvbornot.com#16]
Received the following email from https://groundfloor.us

Dear {name},

With the media broadly reporting on the FDIC taking over Silicon Valley Bank (SVB) yesterday, we thought all of our customers would appreciate reassurance that Groundfloor has zero exposure to that financial institution. None of our accounts are or have ever been held there. We have no banking nor any other relationship with SVB, and are not aware of any indirect dependencies on SVB via third parties that would interfere with our operations or pose any risk to our customers or company.

 

Groundfloor's primary banking relationship is with Truist, the nation's 7th largest bank with over $500 billion in assets. Customer cash held in your Groundfloor investor account is FDIC insured for the benefit of each individual customer up to the federal program limit. 

 

Unlike most investment platforms, Groundfloor files annual audited financials under the regulatory oversight of the U.S. Securities & Exchange Commission, and has done so since 2015. If you are interested, our 2022 statements are available for download via the agency's EDGAR website.

 

While Groundfloor is not directly affected by yesterday’s events, we are very aware of the impact this development could have on innocent bystanders to this latest disruption in our nation’s financial system. Many of us know people who are having to deal with this and we are doing what we can to help and support them.

Please reach out to our customer success team (support@groundfloor.us) with any questions or concerns you may have about how this situation relates to your business with us.

 

Sincerely, 

Groundfloor Investor Services

**Comment by ghuntley** [comment]
thank you. added via https://github.com/ghuntley/affectedbysvbornot.com/pull/17
